/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_op1_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (op1_1_svc(result, rqstp));
}

int
_op2_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (op2_1_svc(*argp, result, rqstp));
}

int
_op3_1 (op3_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (op3_1_svc(argp->key, argp->arg2, argp->value2, argp->value3, result, rqstp));
}

int
_op4_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (op4_1_svc(*argp, result, rqstp));
}

int
_op5_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (op5_1_svc(*argp, result, rqstp));
}

int
_op6_1 (op6_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (op6_1_svc(argp->key, argp->arg2, argp->value2, argp->value3, result, rqstp));
}

int
_op7_1 (op7_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (op7_1_svc(argp->key1, argp->key2, result, rqstp));
}

static void
claves_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int op2_1_arg;
		op3_1_argument op3_1_arg;
		int op4_1_arg;
		int op5_1_arg;
		op6_1_argument op6_1_arg;
		op7_1_argument op7_1_arg;
	} argument;
	union {
		int op1_1_res;
		int op2_1_res;
		int op3_1_res;
		char *op4_1_res;
		int op5_1_res;
		int op6_1_res;
		int op7_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case op1:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_op1_1;
		break;

	case op2:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_op2_1;
		break;

	case op3:
		_xdr_argument = (xdrproc_t) xdr_op3_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_op3_1;
		break;

	case op4:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_op4_1;
		break;

	case op5:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_op5_1;
		break;

	case op6:
		_xdr_argument = (xdrproc_t) xdr_op6_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_op6_1;
		break;

	case op7:
		_xdr_argument = (xdrproc_t) xdr_op7_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_op7_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!claves_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CLAVES, OPERACIONESVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CLAVES, OPERACIONESVER, claves_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CLAVES, OPERACIONESVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CLAVES, OPERACIONESVER, claves_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CLAVES, OPERACIONESVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
