/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES_H_RPCGEN
#define _CLAVES_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct op3_1_argument {
	int key;
	char *arg2;
	int value2;
	double value3;
};
typedef struct op3_1_argument op3_1_argument;

struct op6_1_argument {
	int key;
	char *arg2;
	int value2;
	double value3;
};
typedef struct op6_1_argument op6_1_argument;

struct op7_1_argument {
	int key1;
	int key2;
};
typedef struct op7_1_argument op7_1_argument;

#define CLAVES 99
#define OPERACIONESVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define op1 1
extern  enum clnt_stat op1_1(int *, CLIENT *);
extern  bool_t op1_1_svc(int *, struct svc_req *);
#define op2 2
extern  enum clnt_stat op2_1(int , int *, CLIENT *);
extern  bool_t op2_1_svc(int , int *, struct svc_req *);
#define op3 3
extern  enum clnt_stat op3_1(int , char *, int , double , int *, CLIENT *);
extern  bool_t op3_1_svc(int , char *, int , double , int *, struct svc_req *);
#define op4 4
extern  enum clnt_stat op4_1(int , char **, CLIENT *);
extern  bool_t op4_1_svc(int , char **, struct svc_req *);
#define op5 5
extern  enum clnt_stat op5_1(int , int *, CLIENT *);
extern  bool_t op5_1_svc(int , int *, struct svc_req *);
#define op6 6
extern  enum clnt_stat op6_1(int , char *, int , double , int *, CLIENT *);
extern  bool_t op6_1_svc(int , char *, int , double , int *, struct svc_req *);
#define op7 7
extern  enum clnt_stat op7_1(int , int , int *, CLIENT *);
extern  bool_t op7_1_svc(int , int , int *, struct svc_req *);
extern int claves_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define op1 1
extern  enum clnt_stat op1_1();
extern  bool_t op1_1_svc();
#define op2 2
extern  enum clnt_stat op2_1();
extern  bool_t op2_1_svc();
#define op3 3
extern  enum clnt_stat op3_1();
extern  bool_t op3_1_svc();
#define op4 4
extern  enum clnt_stat op4_1();
extern  bool_t op4_1_svc();
#define op5 5
extern  enum clnt_stat op5_1();
extern  bool_t op5_1_svc();
#define op6 6
extern  enum clnt_stat op6_1();
extern  bool_t op6_1_svc();
#define op7 7
extern  enum clnt_stat op7_1();
extern  bool_t op7_1_svc();
extern int claves_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_op3_1_argument (XDR *, op3_1_argument*);
extern  bool_t xdr_op6_1_argument (XDR *, op6_1_argument*);
extern  bool_t xdr_op7_1_argument (XDR *, op7_1_argument*);

#else /* K&R C */
extern bool_t xdr_op3_1_argument ();
extern bool_t xdr_op6_1_argument ();
extern bool_t xdr_op7_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES_H_RPCGEN */
