/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves.h"
#include "operaciones/operaciones.h"

bool_t
op1_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	*result = init();
	return retval;
}

bool_t
op2_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	*result = exist(key);
	return retval;
}

bool_t
op3_1_svc(int key, char *arg2, int value2, double value3, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	*result = set_value(key, arg2, value2, value3);
	return retval;
}

bool_t
op4_1_svc(int key, char **result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	char *value1;
	int *value2;
	double *value3;
	int res;
	res = get_value(key, value1, value2, value3);
	if (res == 0) {
		sprintf(*result, "%d %s %d %f", res, value1, *value2, *value3);
	} else {
		sprintf(*result, "%d", res);
	}
	return retval;
}

bool_t
op5_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	*result = delete_value(key);
	return retval;
}

bool_t
op6_1_svc(int key, char *arg2, int value2, double value3, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	*result = modify_value(key, arg2, value2, value3);
	return retval;
}

bool_t
op7_1_svc(int key1, int key2, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	*result = copy_key(key1, key2);
	return retval;
}

int
claves_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
