/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "claves.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
op1_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, op1, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
op2_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, op2,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
op3_1(int key, char *arg2, int value2, double value3, int *clnt_res,  CLIENT *clnt)
{
	op3_1_argument arg;
	arg.key = key;
	arg.arg2 = arg2;
	arg.value2 = value2;
	arg.value3 = value3;
	return (clnt_call (clnt, op3, (xdrproc_t) xdr_op3_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
op4_1(int key, char **clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, op4,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
op5_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, op5,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
op6_1(int key, char *arg2, int value2, double value3, int *clnt_res,  CLIENT *clnt)
{
	op6_1_argument arg;
	arg.key = key;
	arg.arg2 = arg2;
	arg.value2 = value2;
	arg.value3 = value3;
	return (clnt_call (clnt, op6, (xdrproc_t) xdr_op6_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
op7_1(int key1, int key2, int *clnt_res,  CLIENT *clnt)
{
	op7_1_argument arg;
	arg.key1 = key1;
	arg.key2 = key2;
	return (clnt_call (clnt, op7, (xdrproc_t) xdr_op7_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
