/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves.h"


void
claves_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	int op2_1_key;
	enum clnt_stat retval_3;
	int result_3;
	int op3_1_key;
	char *op3_1_arg2;
	int op3_1_value2;
	double op3_1_value3;
	enum clnt_stat retval_4;
	char *result_4;
	int op4_1_key;
	enum clnt_stat retval_5;
	int result_5;
	int op5_1_key;
	enum clnt_stat retval_6;
	int result_6;
	int op6_1_key;
	char *op6_1_arg2;
	int op6_1_value2;
	double op6_1_value3;
	enum clnt_stat retval_7;
	int result_7;
	int op7_1_key1;
	int op7_1_key2;

#ifndef	DEBUG
	clnt = clnt_create (host, CLAVES, OPERACIONESVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = op1_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = op2_1(op2_1_key, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = op3_1(op3_1_key, op3_1_arg2, op3_1_value2, op3_1_value3, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = op4_1(op4_1_key, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = op5_1(op5_1_key, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = op6_1(op6_1_key, op6_1_arg2, op6_1_value2, op6_1_value3, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = op7_1(op7_1_key1, op7_1_key2, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	claves_1 (host);
exit (0);
}
